(feat) adding a rich assistant protocol
overmindtech/sdp pull request #244
Opened 2024-08-12 19:04 UTC by tphoney

2024-08-13 07:16 UTC, dylanratcliffe reviewed
I like the structure

2024-08-13 07:16 UTC, dylanratcliffe commented on gateway.proto
> +message ToolMetaData {
```suggestion
message ToolMetadata {
```

2024-08-13 07:16 UTC, dylanratcliffe commented on gateway.proto
> +    ToolMetaData metaData = 1;
```suggestion
    ToolMetadata metadata = 1;
```

2024-08-13 07:16 UTC, dylanratcliffe commented on gateway.proto
> +   int32 numberItems = 1;
These will need an ID to correlate them with the `QueryToolCall` right?

2024-08-13 07:16 UTC, dylanratcliffe commented on gateway.proto
> +    ToolMetaData metaData = 1;
```suggestion
    ToolMetadata metadata = 1;
```

2024-08-13 12:13 UTC, tphoney commented on gateway.proto
> +   int32 numberItems = 1;
so the parent contains metadata, that has the caller_id
```
message ToolCall {
    ToolMetaData metaData = 1;
    oneof call_type {
        QueryToolCall query = 2;
    }
}
```

2024-08-13 13:58 UTC, tphoney commented
@dylanratcliffe @getinnocuous @DavidS-ovm, good for review baring,  one thing. 
the link to open the change, will the backend generate the link ? it is not part of the change metadata/properties. or do we just need to pass an id

2024-08-13 14:01 UTC, dylanratcliffe commented
@tphoney We just need to pass the UUID of the change and the frontend can do the rest

2024-08-13 14:04 UTC, DavidS-ovm approved these changes
Only one minor nit and finalizing the change id

2024-08-13 14:04 UTC, DavidS-ovm commented on gateway.proto
> +message ChangesByReference {
```suggestion
message ChangesByReferenceToolCall {
```

?

2024-08-13 14:12 UTC, dylanratcliffe requested changes

2024-08-13 14:12 UTC, dylanratcliffe commented on gateway.proto
> +        ToolResponse toolResponse = 20;
I'd be tempted to rename these to `ToolStarted` and `ToolFinished` to make them sound a bit more "informational"

2024-08-13 14:12 UTC, dylanratcliffe commented on gateway.proto
> +message RelationshipToolResponse {
This should return just a number of items, same as for query

2024-08-13 14:12 UTC, dylanratcliffe commented on gateway.proto
> +    string scope = 3;
We shouldn't need these three again right? The UI already has them from the `ChangesByReferenceToolCall`

2024-08-13 14:12 UTC, dylanratcliffe commented on gateway.proto
> +message ChangesByReference {
I think this needs renaming, maybe `ChangeSummaryCard`? Doesn't have to be this exactly, but it definitely shouldn't be plural since each of these messages represents one change, and the fact that it was found by reference doesn't really matter to this particular data so I'd be tempted not to inlcude it

2024-08-13 14:31 UTC, getinnocuous commented on gateway.proto
> +    string scope = 3;
> @getinnocuous would it be easier to send this info again, or easier to pull it from the start card.

As long as there is a stable reference to the original call we can get it from there.

2024-08-13 14:37 UTC, DavidS-ovm approved these changes

2024-08-13 14:37 UTC, DavidS-ovm commented on gateway.proto
> +   int32 numberItems = 1;
```suggestion
   int32 numItems = 1;
```

2024-08-13 14:37 UTC, DavidS-ovm commented on gateway.proto
> +    int32 numberItems = 1;
```suggestion
    int32 numItems = 1;
```

2024-08-13 14:51 UTC, dylanratcliffe requested changes
Suggesting we change all the references to either `Start` or `Finish` to unify

2024-08-13 14:51 UTC, dylanratcliffe commented on gateway.proto
> +        QueryToolCall query = 2;
```suggestion
        QueryToolStart query = 2;
```

2024-08-13 14:51 UTC, dylanratcliffe commented on gateway.proto
> +        RelationshipToolCall relationship = 3;
```suggestion
        RelationshipToolStart relationship = 3;
```

2024-08-13 14:51 UTC, dylanratcliffe commented on gateway.proto
> +        ChangesByReferenceToolCall changesByReference = 4;
```suggestion
        ChangesByReferenceToolStart changesByReference = 4;
```

2024-08-13 14:51 UTC, dylanratcliffe commented on gateway.proto
> +message QueryToolCall {
```suggestion
message QueryToolStart {
```

2024-08-13 14:51 UTC, dylanratcliffe commented on gateway.proto
> +message RelationshipToolCall {
```suggestion
message RelationshipToolStart {
```

2024-08-13 14:51 UTC, dylanratcliffe commented on gateway.proto
> +message RelationshipToolResponse {
```suggestion
message RelationshipToolFinish {
```

2024-08-13 14:51 UTC, dylanratcliffe commented on gateway.proto
> +message ChangesByReferenceToolCall {
```suggestion
message ChangesByReferenceToolStart {
```

2024-08-13 14:51 UTC, dylanratcliffe commented on gateway.proto
> +message QueryToolResponse {
```suggestion
message QueryToolFinish {
```

2024-08-13 14:51 UTC, dylanratcliffe commented on gateway.proto
> +message ChangesByReferenceToolResponse {
```suggestion
message ChangesByReferenceToolFinish {
```

2024-08-13 14:51 UTC, dylanratcliffe commented on gateway.proto
> +        QueryToolResponse query = 2;
```suggestion
        QueryToolFinish query = 2;
```

2024-08-13 14:51 UTC, dylanratcliffe commented on gateway.proto
> +        RelationshipToolResponse relationship = 3;
```suggestion
        RelationshipToolFinish relationship = 3;
```

2024-08-13 14:51 UTC, dylanratcliffe commented on gateway.proto
> +        ChangesByReferenceToolResponse changesByReference = 4;
```suggestion
        ChangesByReferenceToolFinish changesByReference = 4;
```

2024-08-14 13:18 UTC, DavidS-ovm approved these changes
It's the final countdown!

2024-08-14 13:51 UTC, merged