Implement QueryStatus and connect that to BookmarkLoadResult
overmindtech/sdp pull request #57
Opened 2023-04-20 17:00 UTC by DavidS-om

2023-04-20 17:45 UTC, dylanratcliffe approved these changes
I like this implementation, will need tickets created to mkae sure the TS and Go libraries both support it but this will help with progress tracking in the UI too

2023-04-20 17:54 UTC, dylanratcliffe requested changes
Changed my ind!

2023-04-20 17:54 UTC, dylanratcliffe commented on gateway.proto
> +    repeated bytes startedQueries = 3;
Whoops missed this. I don't like the idea of multi-layering the serialisation, I think this should be just a `repeated Query`

2023-04-20 18:46 UTC, DavidS-om commented on gateway.proto
> +    repeated bytes startedQueries = 3;
That's only UUIDs, not full queries. Maybe:
```suggestion
    repeated bytes startedQueryUUIDs = 3;
```
?

2023-04-20 18:53 UTC, dylanratcliffe commented on gateway.proto
> +    repeated bytes startedQueries = 3;
Ohhhhh Yeah let's do that

2023-04-20 18:53 UTC, dylanratcliffe approved these changes

2023-04-21 07:00 UTC, merged

2023-04-21 07:06 UTC, DavidS-om commented
> I like this implementation, will need tickets created to mkae sure the TS and Go libraries both support it but this will help with progress tracking in the UI too

https://github.com/overmindtech/sdp-js/pull/88 has the sdp-js bits. for sdp-go, I'll mature the WS client a bit in api-server before publishing it here, unless you had any other requirements?