Change-lifecycle
overmindtech/sdp pull request #61
Opened 2023-04-22 10:22 UTC by dylanratcliffe

Draft PR for change lifecycle RPCs. This will be updated with more info about having server-streaming RPCs will affect the client and server libraries

2023-04-23 13:53 UTC, getinnocuous approved these changes

2023-04-24 07:35 UTC, DavidS-om requested changes
Details in comments

2023-04-24 07:35 UTC, DavidS-om commented on changes.proto
> +  rpc StartChnage(StartChangeRequest) returns (stream StartChangeResponse);
```suggestion
  rpc StartChange(StartChangeRequest) returns (stream StartChangeResponse);
```

2023-04-24 07:35 UTC, DavidS-om commented on changes.proto
> +  rpc CalculateBlastRadius(CalculateBlastRadiusRequest) returns (stream CalculateBlastRadiusResponse);
The comment needs to explain what the contents of the response stream are. e.g.:
```suggestion
  // Calculates the blast radius of a change using the
  // `affectedItemsBookmarkUUID` as the starting point. If the
  // `affectedItemsBookmarkUUID` is blank, this will return an error.
  // Returns a stream of status updates. The response stream closes when all calculating has been done.
  // Executing this RPC will move the Change to the `STATUS_DEFINING` state or return an error.
  rpc CalculateBlastRadius(CalculateBlastRadiusRequest) returns (stream CalculateBlastRadiusResponse);
```

2023-04-24 07:35 UTC, DavidS-om commented on changes.proto
> +message CalculateBlastRadiusRequest {}
How does the Change which has `affectedItemsBookmarkUUID` for the calculation get identified here?

2023-04-24 13:08 UTC, DavidS-om commented on changes.proto
> +  rpc CalculateBlastRadius(CalculateBlastRadiusRequest) returns (stream CalculateBlastRadiusResponse);
Apologies - another question: what happens when the referenced Change is not in STATUS_UNSPECIFIED?

2023-04-24 13:13 UTC, dylanratcliffe commented on changes.proto
> +  rpc CalculateBlastRadius(CalculateBlastRadiusRequest) returns (stream CalculateBlastRadiusResponse);
Added a commit that adds `force` to the request. If set, it'll be recalculated, the the request doesn't contain force and the status isn't `UNSPECIFIED` the request will error

2023-04-24 13:13 UTC, DavidS-om approved these changes

2023-04-24 13:29 UTC, merged